/* Chapter 8 (boss) minigame – Network Doctor: diagnose the root cause from evidence and pick the fix */
(function (OG) {
  const { el, pick, randi, shuffle } = OG;
  const cli = s => `<div class="cli" style="margin:6px 0;font-size:12.5px">${s}</div>`;

  // t: title, sym: symptom, ev: evidence html, cause: [correct, w1, w2, w3], fix: [correct, w1, w2, w3], why
  const BANK = [
    { id: 'timers', lvl: 1, t: 'שכנות לא נוצרת בין R1 ל-R2', sym: 'טבלת השכנים ריקה. הממשקים UP והכתובות באותה רשת.', ev: () => cli(`R1#show ip ospf interface fa0/0\n  Timer intervals configured, <span class="hl">Hello 10, Dead 40</span>, Wait 40, Retransmit 5\n\nR2#show ip ospf interface fa0/0\n  Timer intervals configured, <span class="hl">Hello 5, Dead 20</span>, Wait 20, Retransmit 5`), cause: ['טיימרי Hello/Dead שונים בין הנתבים', 'Area ID שונה', 'Router-ID כפול', 'Reference Bandwidth שונה'], fix: ['ip ospf hello-interval 10 ‏+ ip ospf dead-interval 40 על R2', 'router-id 3.3.3.3 על R2', 'passive-interface fa0/0 על R2', 'auto-cost reference-bandwidth 1000'], why: 'הטיימרים חייבים להיות זהים בשני הצדדים.' },
    { id: 'area', lvl: 1, t: 'R3 ו-R4 לא הופכים לשכנים', sym: 'הכול נראה תקין פיזית, אין שכנות.', ev: () => cli(`R3#show ip protocols\n  Routing for Networks:\n    10.0.34.0 0.0.0.255 <span class="hl">area 0</span>\n\nR4#show ip protocols\n  Routing for Networks:\n    10.0.34.0 0.0.0.255 <span class="hl">area 1</span>`), cause: ['Area ID שונה בין הנתבים', 'מסכת רשת שונה', 'Priority שונה', 'אין ברירת מחדל'], fix: ['לתקן את R4: network 10.0.34.0 0.0.0.255 area 0', 'להפעיל default-information originate', 'ip ospf priority 0', 'bandwidth 1000000'], why: 'שני הצדדים של הקו חייבים להיות באותו Area.' },
    { id: 'mask', lvl: 1, t: 'שכנות נכשלת על קו אחד', sym: 'Hello נשלחים, אבל השכן לא מופיע.', ev: () => cli(`R1#show ip interface brief\nFastEthernet0/0   10.0.12.1   <span class="hl">/24</span>  up   up\n\nR2#show ip interface brief\nFastEthernet0/0   10.0.12.2   <span class="hl">/25</span>  up   up`), cause: ['מסכות רשת שונות בין שני צידי הקו', 'Area שונה', 'אין Loopback', 'Hello=5'], fix: ['ליישר את המסכה ב-R2 ל-255.255.255.0', 'להגדיל priority', 'לשנות process id', 'להפעיל passive-interface'], why: 'הרשת והמסכה חייבות להתאים.' },
    { id: 'passive', lvl: 1, t: 'הקו בין R1 ל-R5 שקט', sym: 'הממשק gi0/0 UP, אבל R5 לא ברשימת השכנים של R1.', ev: () => cli(`R1#show ip protocols\n  Routing for Networks:\n    10.0.15.0 0.0.0.255 area 0\n  <span class="hl">Passive Interface(s):\n    GigabitEthernet0/0</span>`), cause: ['הממשק gi0/0 מוגדר passive ולכן לא שולח Hello', 'חסר Router-ID', 'Cost גבוה', 'חסר Area 0'], fix: ['no passive-interface gi0/0', 'router-id 5.5.5.5', 'auto-cost reference-bandwidth 100', 'ip ospf cost 1'], why: 'passive חוסם Hello ולכן אין שכנות.' },
    { id: 'down', lvl: 1, t: 'נתב R6 לא משתתף ב-OSPF בכלל', sym: 'אין שום מידע OSPF על הממשק gi0/1.', ev: () => cli(`R6#show ip protocols\n  Routing for Networks:\n    <span class="hl">192.168.23.0 0.0.0.0 area 0</span>\n\nR6#show ip interface brief\nGigabitEthernet0/1   192.168.23.6   up   up`), cause: ['ה-Wildcard 0.0.0.0 מתאים רק לכתובת 192.168.23.0 עצמה, לא לכתובת הממשק', 'הממשק למטה', 'Priority 0', 'אזור חסר'], fix: ['network 192.168.23.0 0.0.0.255 area 0', 'ip ospf priority 255', 'no passive-interface default', 'router-id 6.6.6.6'], why: 'Wildcard 0.0.0.0 דורש התאמה מלאה לכתובת. צריך 0.0.0.255 כדי לתפוס את כל הרשת.' },
    { id: 'rid', lvl: 2, t: 'שני נתבים כמעט שכנים, ויש בלגן ב-LSDB', sym: 'כל נתב מתלונן על Router-ID כפול.', ev: () => cli(`R1#show ip ospf\n Routing Process "ospf 1" with ID <span class="hl">1.1.1.1</span>\n\nR2#show ip ospf\n Routing Process "ospf 1" with ID <span class="hl">1.1.1.1</span>`), cause: ['Router-ID כפול – חייב להיות ייחודי בין שכנים', 'Area ID שונה', 'טיימרים שונים', 'אימות שונה'], fix: ['router-id 2.2.2.2 על R2 ואז clear ip ospf process', 'ip ospf hello-interval 5', 'passive-interface default', 'מחיקת Area 0'], why: 'Router-ID כפול בין שכנים שובר את OSPF. אחרי שינוי מפעילים מחדש את התהליך.' },
    { id: 'auth', lvl: 2, t: 'R2 ו-R3 לא מתחברים אחרי "הקשחת אבטחה"', sym: 'מישהו הפעיל אימות MD5 על R2.', ev: () => cli(`R2#show ip ospf interface gi0/0\n  <span class="hl">Message digest authentication enabled</span>\n    Youngest key id is 1\n\nR3#show ip ospf interface gi0/0\n  (no authentication information)`), cause: ['אימות MD5 מוגדר רק בצד אחד', 'Priority שונה', 'Reference BW', 'Router-ID'], fix: ['להגדיר אימות MD5 עם אותו מפתח גם ב-R3', 'ip ospf cost 1', 'maximum-paths 8', 'passive-interface gi0/0'], why: 'אם יש אימות – הסיסמה והסוג חייבים להיות זהים בשני הצדדים.' },
    { id: 'stub', lvl: 3, t: 'שכנות מתקלקלת בין ABR ל-R7 באזור 1', sym: 'Area ID תואם, טיימרים תואמים, ועדיין אין שכנות.', ev: () => cli(`ABR#show ip ospf\n    Area 1\n      <span class="hl">It is a stub area</span>\n\nR7#show ip ospf\n    Area 1\n      <span class="hl">(normal area)</span>`), cause: ['סוג האזור (Stub flag) שונה בין הנתבים', 'Router-ID כפול', 'מסכה שונה', 'הממשק passive'], fix: ['להגדיר area 1 stub גם על R7', 'ip ospf priority 0', 'שינוי Hello ל-5', 'router-id חדש'], why: 'שדה ה-Stub flag בהודעת Hello חייב להיות זהה.' },
    { id: 'net', lvl: 2, t: 'רשת העובדים לא מופיעה בטבלת הניתוב של R4', sym: 'R4 לא יכול להגיע ל-10.5.0.0/16 שיושבת מאחורי R1.', ev: () => cli(`R1#show ip protocols\n  Routing for Networks:\n    192.168.14.0 0.0.0.255 area 0\n\nR1#show ip interface brief\nGi0/1   <span class="hl">10.5.0.1</span>  up  up`), cause: ['הרשת 10.5.0.0 לא פורסמה בפקודת network', 'Hello שונה', 'אין Loopback', 'AD שגוי'], fix: ['network 10.5.0.0 0.0.255.255 area 0', 'default-information originate', 'ip ospf priority 100', 'no passive-interface gi0/1'], why: 'מה שלא תחת network לא מפורסם.' },
    { id: 'cost', lvl: 2, t: 'התנועה עוברת בקו 100Mb במקום בקו Gigabit', sym: 'יש שני נתיבים, וה-OSPF לא מעדיף את המהיר.', ev: () => cli(`R1#show ip ospf interface fa0/0\n  Cost: <span class="hl">1</span>\nR1#show ip ospf interface gi0/0\n  Cost: <span class="hl">1</span>\nR1#show ip protocols | include Reference\n  (Reference bandwidth unit is <span class="hl">100 mbps</span>)`), cause: ['Reference Bandwidth ברירת מחדל (100) – כל קו מ-100Mb ומעלה מקבל Cost 1', 'Priority נמוך', 'שכנות חלקית', 'Router-ID כפול'], fix: ['auto-cost reference-bandwidth 1000 בכל הנתבים', 'ip ospf priority 255', 'passive-interface fa0/0', 'clear ip route *'], why: 'הגדלת ה-Reference גורמת לעלויות שונות לקווים שונים.' },
    { id: 'default', lvl: 3, t: 'אין יציאה לאינטרנט משאר הנתבים', sym: 'לנתב הגבול יש default לספק, אבל לשאר הנתבים אין O*E2.', ev: () => cli(`Edge#show ip route static\nS*   0.0.0.0/0 [1/0] via 192.168.100.1\n\nEdge#show running-config | section ospf\nrouter ospf 1\n  network 10.0.0.0 0.255.255.255 area 0\n  <span class="hl">(no default-information originate)</span>`), cause: ['ברירת המחדל לא מפורסמת ב-OSPF (חסר default-information originate)', 'Area שונה', 'Priority', 'MTU'], fix: ['default-information originate', 'ip ospf cost 100', 'area 0 stub', 'router-id 9.9.9.9'], why: 'ip route 0.0.0.0 … על הנתב היוצא + default-information originate כדי להפיץ.' },
    { id: 'abr', lvl: 3, t: 'אזור 3 מנותק – שאר האזורים לא רואים אותו', sym: 'בטבלת הניתוב אין O IA לרשתות של Area 3.', ev: () => cli(`R9#show ip ospf\n It is an area border router\n Number of areas in this router is 2. <span class="hl">Area 1, Area 3</span>\n  (no Area 0 interfaces)`), cause: ['Area 3 לא מחובר ל-Area 0 – כל אזור חייב לעבור דרך ה-Backbone', 'Router-ID כפול', 'Hello שונה', 'אין Loopback'], fix: ['לחבר את Area 3 ל-Area 0 דרך ABR (או Virtual-Link)', 'להוריד Priority ל-0', 'passive-interface default', 'להגדיל reference-bandwidth'], why: 'ב-Multi-Area כל אזור חייב להיות מחובר ל-Area 0.' },
    { id: 'prio0', lvl: 3, t: 'ברשת ה-LAN אין DR וכולם רק 2-WAY', sym: 'בטבלת השכנים: 2WAY/DROTHER בכל השורות, ואין FULL.', ev: () => cli(`R1#show ip ospf neighbor\nNeighbor ID   Pri  State\n2.2.2.2         <span class="hl">0</span>  2WAY/DROTHER\n3.3.3.3         <span class="hl">0</span>  2WAY/DROTHER\n\nR1#show ip ospf interface gi0/0\n  State DROTHER, Priority <span class="hl">0</span>`), cause: ['כל הנתבים עם Priority 0 – אף אחד לא יכול להיות DR/BDR', 'הטיימרים שונים', 'ה-AD גבוה', 'Router-ID כפול'], fix: ['ip ospf priority 1 (או יותר) על לפחות נתב אחד', 'passive-interface gi0/0', 'router-id חדש', 'auto-cost reference-bandwidth 1000'], why: 'בלי DR/BDR ברשת Multi-Access אין שכנות FULL.' },
    { id: 'ad', lvl: 3, t: 'אחרי החלפת קו, התנועה עדיין בנתיב הישן', sym: 'OSPF מכיר את המסלול החדש, אבל הטבלה לא משתמשת בו.', ev: () => cli(`R1#show ip route 10.9.0.0\nRouting entry for 10.9.0.0/24\n  <span class="hl">S    10.9.0.0/24 [1/0] via 10.0.1.2</span>   (static, old link)\n\nR1#show ip ospf database | include 10.9.0.0\n  10.9.0.0  (learned via OSPF, cost 20)`), cause: ['ניתוב סטטי ישן (AD 1) מנצח את OSPF (AD 110)', 'Priority שונה', 'Dead interval', 'Router-ID'], fix: ['למחוק את הסטטי (no ip route …) או לתת לו AD גבוה', 'ip ospf hello-interval 5', 'router-id 7.7.7.7', 'area 0 stub'], why: 'AD נמוך מנצח. הסטטי נשאר ונהרס ההחלטה.' }
  ];

  OG.games.ch8 = {
    title: 'רופא הרשת', story: 'קריאות חירום זורמות למרכז הבקרה! לכל תקלה יש <b>ראיות</b> (פלט show). אבחנו את סיבת השורש – ובשלב הבא בחרו את התיקון.',
    how: { 1: 'חמש תקלות בסיסיות – בחרו את הסיבה הנכונה לפי הראיות.', 2: 'שלב כפול: קודם הסיבה, אחר כך הפקודה שמתקנת.', 3: 'תקלות מאתגרות יותר (Stub, AD, Area 0, Priority 0, ברירת מחדל) – אבחון ותיקון.' },
    cfg: { 1: { tasks: 5, lives: 3, time: 160 }, 2: { tasks: 5, lives: 3, time: 200 }, 3: { tasks: 6, lives: 3, time: 240 } },
    help: 'קראו את הראיות ובחרו תשובה',
    start(stage, level, sh) {
      const root = el('div', { style: { position: 'absolute', inset: 0, display: 'flex', alignItems: 'center', justifyContent: 'center', padding: '10px', overflow: 'auto' } }); stage.append(root);
      const card = el('div.panel', { style: { width: 'min(900px,98%)' } }); root.append(card);
      const pool = level === 1 ? BANK.filter(b => b.lvl === 1) : level === 2 ? BANK.filter(b => b.lvl <= 2) : BANK.filter(b => b.lvl >= 2);
      const order = shuffle(pool); let n = 0;
      function render() {
        const t = order[n % order.length]; n++; let step = 1; card.innerHTML = '';
        card.append(el('div.row', el('span.tag', { text: '🚨 קריאה #' + n }), el('b', { text: t.t })), el('div.muted', { style: { margin: '6px 0' }, text: t.sym }), el('div', { html: t.ev() }));
        const q = el('div', { style: { marginTop: '8px' } }); card.append(q);
        function ask(title, opts, correct, onRes) {
          q.innerHTML = ''; q.append(el('div', { style: { fontWeight: 800, fontSize: '18px', margin: '6px 0' }, html: title }));
          let locked = false; const ord = shuffle(opts.map((o, i) => i)); const fb = el('div.fb', { style: { display: 'none' } });
          ord.forEach(i => { const b = el('button.opt', { html: opts[i], onclick() { if (locked) return; locked = true; OG.snd.init(); const ok = i === 0; b.classList.add(ok ? 'ok' : 'no'); if (!ok) { OG.$$('.opt', q).forEach((x, k) => { if (ord[k] === 0) x.classList.add('ok'); }); } fb.style.display = ''; fb.className = 'fb ' + (ok ? 'ok' : 'no'); fb.innerHTML = (ok ? '✅ ' : '❌ התשובה הנכונה מסומנת. ') + t.why; onRes(ok); } }); q.append(b); }); q.append(fb);
        }
        const finishTicket = ok => { if (ok) sh.correct({ x: 400, y: 100 }); else sh.wrong({ advance: true, x: 400, y: 100 }); setTimeout(() => { if (!sh.ended) render(); }, ok ? 1600 : 3600); };
        ask('מה הסיבה לתקלה?', t.cause, 0, ok => { if (level === 1) { finishTicket(ok); return; } if (!ok) { finishTicket(false); return; } setTimeout(() => ask('איזה תיקון נכון?', t.fix, 0, ok2 => finishTicket(ok2)), 900); });
      }
      render();
      return { destroy() { root.remove(); } };
    }
  };
})(window.OG);
